spring:
  profiles:
    active: dev

server:
  port: 8003

dubbo:
  scan:
    base-packages: com.example.testing.controller
  protocols:
    dubbo:
      name: dubbo
      port: -1
  registry:
    address: spring-cloud://47.98.62.6:8848
  application:
    qos-enable: false
  cloud:
    subscribed-services: testing-provider-example

local:
  name: xiao
